In [306]:
from getData import get_data
from technical_indicator import calculate_LR, MACD, RSI, BB, ATR, ADX, RENKO
from Returns import cummulative_returns, CAGR, volatility, SHARPE, SORTINO, MAXDROWDOWN, CALMAR

import matplotlib.pyplot as plt
import yfinance as yf
import pandas as pd
import numpy as np
import datetime as dt
%load_ext autoreload
%autoreload 2
pd.set_option('mode.chained_assignment', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [307]:
data = yf.download(tickers= 'RELIANCE.NS', period = '1y', interval = '1d')

[*********************100%***********************]  1 of 1 completed

In [308]:
def run_all_2():
    # data = yf.download(tickers= 'RELIANCE.NS', period = '1mo', interval = '5m')   
    calculate_LR(data)
    RSI(data)
    cummulative_returns(data)
    MACD(data)
    ATR(data)
    ADX(data)
    CAGR(data)
    volatility(data)
    SHARPE(data, 0.04)
    SORTINO(data, 0.03)
    MAXDROWDOWN(data)
    CALMAR(data)
    return data

In [309]:
run_all_2()
data

Price,Close,High,Low,Open,Volume,STD,+1STD,-1STD,+2STD,-2STD,...,ADX,CAGR,VOL,SHARPE,SORTINO,cum_return,cum_roll_max,drawdown,Max_DD,CALMAR
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,,,,,...,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,,,
2024-02-21,1457.770996,1478.455188,1447.689758,1464.028425,12720292,131.302001,1666.665161,1404.061160,1797.967162,1272.759159,...,NaN,15.102779,0.21824,69.019174,65.315963,NaN,NaN,NaN,24.1983,0.624126
2024-02-22,1471.725952,1474.904256,1448.136621,1458.217980,18493728,131.302001,1665.918111,1403.314109,1797.220111,1272.012109,...,NaN,15.102779,0.21824,69.019174,65.315963,1.009573,1.009573,0.000000,24.1983,0.624126
2024-02-23,1483.520630,1487.419126,1473.315116,1479.423535,14438584,131.302001,1665.171060,1402.567059,1796.473061,1271.265058,...,NaN,15.102779,0.21824,69.019174,65.315963,1.017664,1.017664,0.000000,24.1983,0.624126
2024-02-26,1477.263184,1484.414548,1472.470873,1483.446168,7513106,131.302001,1662.929909,1400.325908,1794.231909,1269.023907,...,NaN,15.102779,0.21824,69.019174,65.315963,1.013371,1.017664,0.004292,24.1983,0.624126
2024-02-27,1475.599609,1489.802797,1468.051048,1472.992367,10826044,131.302001,1662.182858,1399.578857,1793.484859,1268.276857,...,NaN,15.102779,0.21824,69.019174,65.315963,1.012230,1.017664,0.005434,24.1983,0.624126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-17,1224.900024,1227.500000,1204.500000,1211.099976,8166683,131.302001,1396.232905,1133.628904,1527.534905,1002.326903,...,14.870570,15.102779,0.21824,69.019174,65.315963,0.840255,1.090754,0.250499,24.1983,0.624126
2025-02-18,1225.400024,1229.900024,1216.099976,1224.849976,6673250,131.302001,1395.485854,1132.881853,1526.787855,1001.579853,...,15.660332,15.102779,0.21824,69.019174,65.315963,0.840598,1.090754,0.250156,24.1983,0.624126
2025-02-19,1227.449951,1232.750000,1217.550049,1219.500000,6217338,131.302001,1394.738804,1132.134803,1526.040805,1000.832802,...,16.198291,15.102779,0.21824,69.019174,65.315963,0.842005,1.090754,0.248750,24.1983,0.624126
2025-02-20,1233.000000,1239.349976,1222.000000,1223.949951,7795582,131.302001,1393.991754,1131.387753,1525.293754,1000.085752,...,16.266133,15.102779,0.21824,69.019174,65.315963,0.845812,1.090754,0.244942,24.1983,0.624126
2025-02-21,1228.150024,1240.000000,1222.150024,1228.699951,6903419,131.302001,1393.244703,1130.640702,1524.546704,999.338702,...,16.285032,15.102779,0.21824,69.019174,65.315963,0.842485,1.090754,0.248269,24.1983,0.624126

In [279]:
data = pd.DataFrame(data['Close'].values, columns=['Close'])
data['Close']

0      1462.735474
1      1476.737915
2      1488.572754
3      1482.294067
4      1480.624756
          ...
245    1224.900024
246    1225.400024
247    1227.449951
248    1233.000000
249    1228.150024
Name: Close, Length: 250, dtype: float64

Date
2024-02-21    0.629609
2024-02-22    0.629609
2024-02-23    0.629609
2024-02-26    0.629609
2024-02-27    0.629609
                ...
2025-02-17    0.629609
2025-02-18    0.629609
2025-02-19    0.629609
2025-02-20    0.629609
2025-02-21    0.629609
Length: 250, dtype: float64

In [302]:
# CALMAR 
def CALMAR(data):
    data['CALMAR'] = data['CAGR']/data['Max_DD']
    return data

In [303]:
CALMAR(data)

Price,Close,High,Low,Open,Volume,STD,+1STD,-1STD,+2STD,-2STD,...,ADX,CAGR,VOL,SHARPE,SORTINO,cum_return,cum_roll_max,drawdown,Max_DD,CALMAR
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,,,,,...,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,,,
2024-02-21,1462.735474,1483.490106,1452.619903,1469.014213,12720292,133.933451,1675.417760,1407.550858,1809.351211,1273.617407,...,NaN,15.397452,0.218038,70.434752,66.592874,NaN,NaN,NaN,24.455569,0.629609
2024-02-22,1476.737915,1479.927042,1453.068250,1463.183942,18493728,133.933451,1674.650578,1406.783676,1808.584029,1272.850225,...,NaN,15.397452,0.218038,70.434752,66.592874,1.009573,1.009573,0.000000,24.455569,0.629609
2024-02-23,1488.572754,1492.484526,1478.332485,1484.461707,14438584,133.933451,1673.883396,1406.016494,1807.816847,1272.083043,...,NaN,15.397452,0.218038,70.434752,66.592874,1.017664,1.017664,0.000000,24.455569,0.629609
2024-02-26,1482.294067,1489.469786,1477.485437,1488.498109,7513106,133.933451,1671.581849,1403.714947,1805.515301,1269.781496,...,NaN,15.397452,0.218038,70.434752,66.592874,1.013371,1.017664,0.004292,24.455569,0.629609
2024-02-27,1480.624756,1494.876313,1473.050487,1478.008635,10826044,133.933451,1670.814667,1402.947765,1804.748118,1269.014314,...,NaN,15.397452,0.218038,70.434752,66.592874,1.012230,1.017664,0.005434,24.455569,0.629609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-17,1224.900024,1227.500000,1204.500000,1211.099976,8166683,133.933451,1397.697834,1129.830932,1531.631285,995.897481,...,14.874358,15.397452,0.218038,70.434752,66.592874,0.837404,1.090754,0.253351,24.455569,0.629609
2025-02-18,1225.400024,1229.900024,1216.099976,1224.849976,6673250,133.933451,1396.930652,1129.063750,1530.864103,995.130299,...,15.664043,15.397452,0.218038,70.434752,66.592874,0.837745,1.090754,0.253009,24.455569,0.629609
2025-02-19,1227.449951,1232.750000,1217.550049,1219.500000,6217338,133.933451,1396.163470,1128.296567,1530.096921,994.363116,...,16.201926,15.397452,0.218038,70.434752,66.592874,0.839147,1.090754,0.251607,24.455569,0.629609
2025-02-20,1233.000000,1239.349976,1222.000000,1223.949951,7795582,133.933451,1395.396287,1127.529385,1529.329738,993.595934,...,16.269683,15.397452,0.218038,70.434752,66.592874,0.842941,1.090754,0.247813,24.455569,0.629609
2025-02-21,1228.150024,1240.000000,1222.150024,1228.699951,6903419,133.933451,1394.629105,1126.762203,1528.562556,992.828752,...,16.288504,15.397452,0.218038,70.434752,66.592874,0.839626,1.090754,0.251129,24.455569,0.629609

In [286]:
# MAXDRAWDOWN
def MAXDROWDOWN(data):
    # data['return'] = data['Close'].pct_change()
    data['cum_return'] = (1+ data['d_rtn']).cumprod()
    data['cum_roll_max'] = data['cum_return'].cummax()
    data['drawdown'] = data['cum_roll_max'] - data['cum_return']
    data['Max_DD'] = ((data['drawdown']/data['cum_roll_max'])).max()*100
    return data

In [287]:
MAXDROWDOWN(data)

Price,Close,High,Low,Open,Volume,STD,+1STD,-1STD,+2STD,-2STD,...,ADX,CAGR,VOL,SHARPE,SORTINO,cum_roll_max,drawdown,Max_DD,return,cum_return
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,,,,,...,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,,,
2024-02-21,1462.735474,1483.490106,1452.619903,1469.014213,12720292,133.933451,1675.417760,1407.550858,1809.351211,1273.617407,...,NaN,15.397452,0.218038,70.434752,66.592874,NaN,NaN,0.244556,NaN,NaN
2024-02-22,1476.737915,1479.927042,1453.068250,1463.183942,18493728,133.933451,1674.650578,1406.783676,1808.584029,1272.850225,...,NaN,15.397452,0.218038,70.434752,66.592874,1.009573,0.000000,0.244556,0.009573,1.009573
2024-02-23,1488.572754,1492.484526,1478.332485,1484.461707,14438584,133.933451,1673.883396,1406.016494,1807.816847,1272.083043,...,NaN,15.397452,0.218038,70.434752,66.592874,1.017664,0.000000,0.244556,0.008014,1.017664
2024-02-26,1482.294067,1489.469786,1477.485437,1488.498109,7513106,133.933451,1671.581849,1403.714947,1805.515301,1269.781496,...,NaN,15.397452,0.218038,70.434752,66.592874,1.017664,0.004292,0.244556,-0.004218,1.013371
2024-02-27,1480.624756,1494.876313,1473.050487,1478.008635,10826044,133.933451,1670.814667,1402.947765,1804.748118,1269.014314,...,NaN,15.397452,0.218038,70.434752,66.592874,1.017664,0.005434,0.244556,-0.001126,1.012230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-17,1224.900024,1227.500000,1204.500000,1211.099976,8166683,133.933451,1397.697834,1129.830932,1531.631285,995.897481,...,14.874358,15.397452,0.218038,70.434752,66.592874,1.090754,0.253351,0.244556,0.006285,0.837404
2025-02-18,1225.400024,1229.900024,1216.099976,1224.849976,6673250,133.933451,1396.930652,1129.063750,1530.864103,995.130299,...,15.664043,15.397452,0.218038,70.434752,66.592874,1.090754,0.253009,0.244556,0.000408,0.837745
2025-02-19,1227.449951,1232.750000,1217.550049,1219.500000,6217338,133.933451,1396.163470,1128.296567,1530.096921,994.363116,...,16.201926,15.397452,0.218038,70.434752,66.592874,1.090754,0.251607,0.244556,0.001673,0.839147
2025-02-20,1233.000000,1239.349976,1222.000000,1223.949951,7795582,133.933451,1395.396287,1127.529385,1529.329738,993.595934,...,16.269683,15.397452,0.218038,70.434752,66.592874,1.090754,0.247813,0.244556,0.004522,0.842941
2025-02-21,1228.150024,1240.000000,1222.150024,1228.699951,6903419,133.933451,1394.629105,1126.762203,1528.562556,992.828752,...,16.288504,15.397452,0.218038,70.434752,66.592874,1.090754,0.251129,0.244556,-0.003933,0.839626

In [291]:
data = yf.download('RELIANCE.NS', period='1y', interval='1d')
# print(data)

data['return'] = data['Close'].pct_change()
data['cum_return'] = (1+ data['return']).cumprod()
data['cum_roll_max'] = data['cum_return'].cummax()
data['drawdown'] = data['cum_roll_max'] - data['cum_return']
data['Max_DD'] = ((data['drawdown']/data['cum_roll_max'])).max()*100
data

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume,return,cum_return,cum_roll_max,drawdown,Max_DD
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,,,,
Date,,,,,,,,,,
2024-02-21,1462.735474,1483.490106,1452.619903,1469.014213,12720292,NaN,NaN,NaN,NaN,24.455569
2024-02-22,1476.737915,1479.927042,1453.068250,1463.183942,18493728,0.009573,1.009573,1.009573,0.000000,24.455569
2024-02-23,1488.572754,1492.484526,1478.332485,1484.461707,14438584,0.008014,1.017664,1.017664,0.000000,24.455569
2024-02-26,1482.294067,1489.469786,1477.485437,1488.498109,7513106,-0.004218,1.013371,1.017664,0.004292,24.455569
2024-02-27,1480.624756,1494.876313,1473.050487,1478.008635,10826044,-0.001126,1.012230,1.017664,0.005434,24.455569
...,...,...,...,...,...,...,...,...,...,...
2025-02-17,1224.900024,1227.500000,1204.500000,1211.099976,8166683,0.006285,0.837404,1.090754,0.253351,24.455569
2025-02-18,1225.400024,1229.900024,1216.099976,1224.849976,6673250,0.000408,0.837745,1.090754,0.253009,24.455569
2025-02-19,1227.449951,1232.750000,1217.550049,1219.500000,6217338,0.001673,0.839147,1.090754,0.251607,24.455569
2025-02-20,1233.000000,1239.349976,1222.000000,1223.949951,7795582,0.004522,0.842941,1.090754,0.247813,24.455569
2025-02-21,1228.150024,1240.000000,1222.150024,1228.699951,6903419,-0.003933,0.839626,1.090754,0.251129,24.455569

In [292]:
# data = yf.download(tickers= 'RELIANCE.NS', period = '1mo', interval = '15m')
# hour_data = yf.download(tickers= 'RELIANCE.NS', period = '1y', interval = '1h')

In [219]:
# Create a line chart
import plotly.graph_objects as go
fig = go.Figure()

# Add multiple lines (traces) to the figure
for key in dict_stock:
    fig.add_trace(go.Scatter(
        x=dict_stock[key].index,
        y=dict_stock[key]['cum_rtn'],
        mode='lines',  # Set the mode to 'lines' for a line chart
        name=key# Use the name for each line from the dictionary
    ))

# Customize the layout
fig.update_layout(
    title="TOP Bank Return",
    xaxis_title="Year",
    yaxis_title="Cumulative Return",
    autosize=False,
    width=1100,
    height=800,
    template='plotly_dark'
)

# Show the plot
fig.show()

NameError: name 'dict_stock' is not defined

In [8]:
data

NameError: name 'data' is not defined