In [268]:
from getData import get_data
from technical_indicator import LR, MACD, RSI, BB, ATR, ADX, RENKO
from Returns import cummulative_returns, CAGR, volatility, SHARPE, SORTINO, MAXDROWDOWN, CALMAR

import matplotlib.pyplot as plt
import yfinance as yf
import pandas as pd
import numpy as np
import datetime as dt
%load_ext autoreload
%autoreload 2
pd.set_option('mode.chained_assignment', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [225]:
# Store data in dictionary
ohlcv_dict = {}
for stock in tickers:
    ohlcv_dict[stock] = get_ohlcv(ticker=stock, period = '5y', interval='1d')


# data = copy.deepcopy(ohlcv_dict)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [269]:

tickers = ['^NSEI', 'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'BHARTIARTL.NS', 'ICICIBANK.NS', 'INFY.NS', 'SBIN.NS', 'HINDUNILVR.NS', 
           'BAJFINANCE.NS',
           'ITC.NS']

In [278]:
data = copy.deepcopy(ohlcv_dict)

In [279]:
# Cummulative Return
for stock in data.keys():
    cummulative_returns(data[stock])

CAGR of ^NSEI is 14.285557503998469
CAGR of RELIANCE.NS is 14.171508273311439
CAGR of TCS.NS is 14.60456355905424
CAGR of HDFCBANK.NS is 7.957837193082318
CAGR of BHARTIARTL.NS is 26.76516277911385
CAGR of ICICIBANK.NS is 19.54587422183993
CAGR of INFY.NS is 21.080361136303804
CAGR of SBIN.NS is 19.22074547006194
CAGR of HINDUNILVR.NS is 1.790773067580087
CAGR of BAJFINANCE.NS is 12.400030694330312
CAGR of ITC.NS is 20.21993288691608

In [284]:
data['RELIANCE.NS']

Price,Close,High,Low,Open,Volume,d_rtn,daily_returns,cum_rtn,CAGR
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,,,
Date,,,,,,,,,
2020-02-24,639.780212,653.970964,637.389265,650.760886,21370214,NaN,NaN,NaN,0.141715
2020-02-25,627.139160,642.636075,624.305396,642.636075,27745062,-0.019758,-0.019758,0.980242,0.141715
2020-02-26,616.335510,625.345884,614.276660,624.305375,29362748,-0.017227,-0.017227,0.963355,0.141715
2020-02-27,613.789673,617.132578,606.151845,614.564468,25054993,-0.004131,-0.004131,0.959376,0.141715
2020-02-28,588.286072,600.838622,586.669979,599.908773,39315769,-0.041551,-0.041551,0.919513,0.141715
...,...,...,...,...,...,...,...,...,...
2025-02-17,1224.900024,1227.500000,1204.500000,1211.099976,8166683,0.006285,0.006285,1.914564,0.141715
2025-02-18,1225.400024,1229.900024,1216.099976,1224.849976,6673250,0.000408,0.000408,1.915345,0.141715
2025-02-19,1227.449951,1232.750000,1217.550049,1219.500000,6217338,0.001673,0.001673,1.918549,0.141715
2025-02-20,1233.000000,1239.349976,1222.000000,1223.949951,7795582,0.004522,0.004522,1.927224,0.141715
2025-02-21,1228.150024,1240.000000,1222.150024,1228.699951,6904025,-0.003933,-0.003933,1.919644,0.141715

In [277]:
((1228.150024/639.780212)**(1/5) )-1

0.13931580867064053